# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'BLEManagerObjc' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for BLEManagerObjc
  
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'JSExtension'
  
  
  target 'BLEManagerObjcTests' do
  inherit! :search_paths
  # Pods for testing
  pod 'OCMock', '~> 3.3'
  pod 'OCHamcrest', '~> 5.4.0'
  pod 'XcodeCoverage','~>1.0'
  end

end
